### ISSUE TITLE
Concourse does not work with stemcell version 3541.x

### ISSUE THREAD

**Issue by joshzarrabi** [concourse/concourse-bosh-deployment#46]
If you use latest of concourse deployment with the latest stemcell you see the following error:
```
runc create: exit status 1: container_linux.go:264: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:44: preparing rootfs caused \\\"permission denied\\\"\""
```

We believe it has to do with the stemcell using 0077 instead of 0022. Newer versions of garden-runc-release seem to work.

**Comment by ljfranklin** [comment]
In addition to bumping to the latest garden, can y'all pin `concourse-deployment` to a specific, vetted stemcell version: https://github.com/concourse/concourse-deployment/blob/934b480f939145b98ce975ed124c39184b2dcf06/cluster/concourse.yml#L106. This would avoid similar breaking changes going forward.

**Comment by dgodd** [comment]
For those looking here for a suggestion of which stemcell version to use. After failing in the above way using 3541.2, I chose to stick on the version I had previously used. I can confirm that  3445.2 works

**Comment by vito** [comment]
I don't think the latest version of Garden-runC (1.11.1) works, either; we saw these errors in our own pipeline and then disabled the stemcell version.

Pretty unhappy with this stemcell bump to be honest. The version numbers don't indicate any level of backwards-incompatibility, and it's pretty hard to find the release notes even if I did think to check (the release is not on the first page of https://github.com/cloudfoundry/bosh/releases and not linked to by bosh.io). Up until now we haven't had to ever specify a stemcell version, and let people roll forward aggressively for security updates/etc., but if it's going to be this unstable/surprising we might have to.

**Comment by dpb587-pivotal** [comment]
@vito FYI, stemcells were split off into their own repo at cloudfoundry/bosh-linux-stemcell-builder where recent versions do have release notes and [3541.2](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/stable-3541.2) does mention this breaking change. Still, perhaps this particular change could have been rolled out in a different way.

I agree though that bosh.io got lazy about surfacing release notes which should be important and helps with this sort of thing. It should definitely be fixed.

Technically it was a major version stemcell which suggests backwards incompatible changes may be present... but historically there have been very few compatibility-breaking stemcells which makes it too easy for us to assume all stemcell updates will be smooth. I think better surfacing of release notes would help quite a bit; but, in general, I don't think it's a safe assumption to reference latest, or even automatically upgrade dependencies across major versions without prior testing and verification within a deployment.

/cc @cppforlife

**Comment by vito** [comment]
@dpb587-pivotal Agreed. But while it was technically a major version bump, it's not really semver. If I remember right, the stemcell versions used to just be Jenkins build numbers, so to me they are *especially* meaningless.

There's generally not much to notice or care about when going version-to-version, and with only two number segments and with the last one being used for security patches, you can't assume anything about the first number since it's also bumped for backwards-compatible changes ("features", in the semver sense)[1]. The releases come often enough that it would be mostly a waste of time to be constantly looking for breaking changes in the release notes. (It would obviously not be a waste of time if there was a "real" major version bump!)

[1]: I might be wrong there, I'm just assuming there's not usually breakage of this magnitude, but it might actually technically be smaller backwards-incompatible things with little to no impact.

**Comment by cppforlife** [comment]
> The releases come often enough that it would be mostly a waste of time to be constantly looking for breaking changes in the release notes. (It would obviously not be a waste of time if there was a "real" major version bump!)

it's real major.minor, we just dont use patch digits right now (but will be for ubuntu-xenial). updates in minors are not breaking (that's how floating stemcells end up working with compiled releases). majors do add breaking features but we try to make it as rare as possible.

**Comment by cppforlife** [comment]
also 3541.4 rolls back umask change since there was an unexpected bpm breakage.

**Comment by bmhkb4** [comment]
So aside from just rolling back to previous stemcells, what is the long term plan here? 3541.4 still has this issue

**Comment by vito** [comment]
We've got a fix in for 3.9.1 (not out yet) and there is also a newer
stemcell that reverts the change that broke everything. So 3.9.1 should
work with 3541.2 and whatever the next version is.

Until then, either unbump your stemcell or go to the latest.

**Comment by cunnie** [comment]
3541.4 appears to have the same problem, i.e. I see in `/var/vcap/sys/log/garden/garden.stdout.log`

```json
{"timestamp":"1519577526.711933136","source":"guardian","message":"guardian.api.garden-server.create.failed","log_level":2,"data":{"error":"runc run: exit status 1: container_linux.go:348: starting container process caused \"process_linux.go:402: container init caused \\\"rootfs_linux.go:46: preparing rootfs caused \\\\\\\"permission denied\\\\\\\"\\\"\"\n","request":{"Handle":"57e474f8-ca2d-4ba3-502f-752b318f147d","GraceTime":0,"RootFSPath":"raw:///var/vcap/data/baggageclaim/volumes/live/52d9e371-bf36-420f-54e7-fd392cfe0039/volume","BindMounts":[{"src_path":"/var/vcap/data/baggageclaim/volumes/live/db79bc67-48fd-4dea-45f8-42b712da859b/volume","dst_path":"/etc/ssl/certs"},{"src_path":"/var/vcap/data/baggageclaim/volumes/live/63afed6a-c6ef-40dc-56ba-23c689064fb9/volume","dst_path":"/scratch","mode":1}],"Network":"","Privileged":false,"Limits":{"bandwidth_limits":{},"cpu_limits":{},"disk_limits":{},"memory_limits":{},"pid_limits":{}}},"session":"3.1.27"}}
```
```bash
cat /var/vcap/bosh/etc/stemcell_version
3541.4
```

**Comment by vito** [comment]
Looks like our fix planned for 3.9.1 isn't enough; reopening.

**Comment by kamoljan** [comment]
+1

**Comment by brightzheng100** [comment]
So what's the suggestion then?

I got the same issue with:
- Concourse: 3.9.2
- garden-runc: 1.12.1
- Stemcell: 3541.5

**Comment by ezraroi** [comment]
any update on this? how can i set the stemcell version on my local ubunto trusty? i am using the concourse binary

**Comment by cunnie** [comment]
@ezraroi I believe the current version of Concourse (3.13.0) successfully runs on stemcell 3586.7. In other words, I think the stemcell issue is resolved. You can check out my personal Concourse if you have doubts:  https://ci.nono.io/

**Comment by sbkg0002** [comment]
When using the concourse binary of 3.14.1 on CoreOS, we still have this issue.

**Comment by FilBot3** [comment]
I am also having this issue on Concourse 4.2.2 getting the same error, but on Oracle Linux UEK R4.

```json
{
  "timestamp":"1550257062.072880745",
  "source":"guardian",
  "message":"guardian.api.garden-server.create.failed",
  "log_level":2,
  "data":{
    "error":"runc run: exit status 1: container_linux.go:348: starting container process caused \"process_linux.go:402: container init caused \\\"rootfs_linux.go:46: preparing rootfs caused \\\\\\\"permission denied\\\\\\\"\\\"\"\n",
    "request":{
      "Handle":"ab1c8bbe-ec8f-4c41-7534-f10e081b5351",
      "GraceTime":0,
      "RootFSPath":"raw:///opt/concourse-ci/volumes/live/f3f53232-bd2a-428b-7cf6-925ea9e080c8/volume/rootfs",
      "BindMounts":[
        {
          "src_path":"/opt/concourse-ci/volumes/live/450737c4-a993-4d97-517a-19e65ee902c1/volume",
          "dst_path":"/scratch",
          "mode":1
        },
        {
          "src_path":"/opt/concourse-ci/volumes/live/00d9a1b3-8ff6-42cb-533f-4f35e70beab1/volume",
          "dst_path":"/tmp/build/dadbfeaa",
          "mode":1
        }
      ],
      "Network":"",
      "Privileged":false,
      "Limits":{
        "bandwidth_limits":{},
        "cpu_limits":{},
        "disk_limits":{},
        "memory_limits":{},
        "pid_limits":{}
      }
    },
    "session":"3.1.47"
  }
}
```
